name: Admin App Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - "admin_app/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "admin_app/**"

jobs:
  user-app-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: admin_app

      # To prevent asset build issues
      - name: Create dummy .env file
        run: touch admin_app/.env

      - name: Run Flutter tests
        run: flutter test
        working-directory: admin_app
